### ISSUE TITLE
radial test cases

### ISSUE THREAD

**Issue by frederikgeth** [power-grid-lib/pglib-opf#30]
It seems none of the test cases in pglib-opf  are radial? That makes it hard to use any of these benchmarks to use/extend them for models that require a consistent definition of upstream/downstream, e.g. as in [1] below.

I recall that the NESTA archive had a /rad m file collection. Was there any discussion on including that in pglib-opf? What happened to it?

[1] Dvorkin, V., Fioretto, F., Van Hentenryck, P., Kazempour, J., & Pinson, P. (2020). Differentially Private Optimal Power Flow for Distribution Grids, 1, 1–9. Retrieved from http://arxiv.org/abs/2004.03921

**Comment by hhijazi** [comment]
I agree that this is an important subset, @ccoffrin any chance on adding those back?

**Comment by ccoffrin** [comment]
When the move from NESTA and PGLib-OPF was happening the task force had a discussion was had about what cases to include and not to include in PGLib-OPF.  The conclusion of that discussion is that these cases should strive to represent real-world transmission system datasets.  Similar in spirit to the cases developed by GRID DATA and the Gird Optimization Competition, they may not be real but they should at least be realistic.  Using this as a guiding rule the Radial (RAD) and Non-Convex Optimization (NCO) cases from NESTA were not included due a lack of realism.  It was also noted at that time that the RAD/NCO these cases were designed by academics to demonstrate specific mathematical properties which were of interest to a fairly small segment of the research community.

I do agree that there is a need for single-phase radial OPF problems, but I also think these should be derived from distribution network datasets, rather than building a subtree from transition datasets (which was the case with the RAD instances).  Maybe an other PGLib repo focused on distribution system optimization could be home for both multi-phase and single-phase radial test cases?

**Comment by frederikgeth** [comment]
Thanks for the clarification! It sounds reasonable that they were dropped then. Deriving radial data sets from the IEEE distribution test feeders sounds like the best path forward indeed.

**Comment by ccoffrin** [comment]
If there is no further discussion, I propose to close this issue.

**Comment by frederikgeth** [comment]
done. thanks!
