### ISSUE TITLE
DC Baselines, Constraints, and Inf

### ISSUE THREAD

**Issue by ElPiloto** [power-grid-lib/pglib-opf#35]
Hello, I have some related questions about the DC OPF baselines.

1. It seems that for many of the typical operating conditions, the DC approximation _better_ minimizes the cost than the full AC solution.  Is this expected?  Does this factor in any constraint violations?

2. In some of the small angle difference cases, the objective values for the DC approximation are listed as "Inf".  Does that indicate a constraint violation?

**Comment by ccoffrin** [comment]
Good questions.

> * It seems that for many of the typical operating conditions, the DC approximation _better_ minimizes the cost than the full AC solution.  Is this expected?  Does this factor in any constraint violations?

This is usually the case because the the DC approximation does not include line power losses (which typically account for 1-10% of power consumption in the system). If you do a more careful accounting for line power losses in an approximate model then you will find the objectives of a linear approximation can be a much closer match the AC model.

> * In some of the small angle difference cases, the objective values for the DC approximation are listed as "Inf".  Does that indicate a constraint violation?

This means that there is solution to linearized power flow equations and network constraints using the DC approximation (i.e., it is infeasible). The implication here is that the DC approximation is not sufficiently accurate to model this particular dataset.

**Comment by ccoffrin** [comment]
What you outline here is mostly correct.  The one clarification I would make is that making the DC solution AC feasible is more than just finding the "missing variables" you have to adjust the active power too, to make it feasible.  You might find this tutorial video series helpful, https://arxiv.org/abs/1807.07227

**Comment by ElPiloto** [comment]
Thanks for the pointer to that video series (which I have watched) and thoughtful responses: this conversation has been really helpful!  I'm going to close the issue now as we've definitely covered my questions.

I do have one final suggestion: is it possible to make available the script(s) that produce the baselines values?  This will make it maximally transparent how these values are generated.  That might be a tall order though.

**Comment by ccoffrin** [comment]
Glad to hear it.

Regarding replicating the baseline values.  There is some documentation in the `BASELINE.md` about this.  If you dig into the PowerModels docs you will see running the AC problem is basically,
```
# one time install
] add JuMP, PowerModels, Ipopt

# running a specific case
using JuMP, PowerModels, Ipopt
solver = optimizer_with_attributes(Ipopt.Optimizer, "tol"=>1e-6)
result = run_ac_opf("case_file.m", solver)
```
For the other models that are discussed the PowerModels documentation and technical report should be sufficient.  And if you want to replicate the timing results you need to setup Ipopt.jl with the suitable MA27 linear algebra library, which appears in the Ipopt.jl docs.

I prefer keeping this documentation in PowerModels, rather than here, to reduce the maintenance burden to keep the documentation accurate.  Hope fully the log of this issue will help interested folks to connect the dots.

**Comment by yasirroni** [comment]
Hi @ccoffrin,  Could you share a separate repo that contains all the scripts to produce the julia results? Preferable that produce the table without the need to copy paste. I'm not julia programmer and it would really help if we are able to just run scripts.

**Comment by ccoffrin** [comment]
Hi @yasirroni, I don't really have some simple script I can share. The instructions above are about as simple as it gets and setting up Ipopt with MA27 is some additional work see this, https://github.com/jump-dev/Ipopt.jl?tab=readme-ov-file#hsl

You may find this repo as a useful as well, https://github.com/lanl-ansi/rosetta-opf
